# Generated by Django 4.2.4 on 2023-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
                ('confirm_password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
